radio_inventory/auth/urls.py
from django.urls import path, include
from auth import views

urlpatterns = [
    path('signup', views.SignUpView.as_view(), name='auth__signup'),
    path('activate/<int:pk>/<str:token>', views.ActivateView.as_view(),
         name='auth__activate'),
    path('django/', include('django.contrib.auth.urls')),
]

radio_inventory/inventory/urls.py
from django.urls import path
from django.views.generic import TemplateView

from inventory import views


urlpatterns = [
    path('location/', views.LocationListView.as_view(),
         name='inventory__location-list'),
    path('location/<int:pk>', views.LocationDetailView.as_view(),
         name='inventory__location-detail'),
    path('location/create', views.LocationCreateView.as_view(),
         name='inventory__location-create'),
    path('location/<int:pk>/update', views.LocationUpdateView.as_view(),
         name='inventory__location-update'),
    path('location/<int:pk>/delete', views.LocationDeleteView.as_view(),
         name='inventory__location-delete'),
    path('location/<int:pk>/label.pdf', views.LocationBarcodeView.as_view(),
         name='inventory__location-barcode'),
    path('location/<int:pk>/connections.pdf',
         views.LocationGraphView.as_view(),
         name='inventory__location-connections'),
    path('location/<int:pk>/device/create',
         views.DeviceCreateView.as_view(initial_kwargs={'location': 'pk'}),
         name='inventory__location-device-create'),

    path('location_image/<int:pk>', views.LocationImageView.as_view(),
         name='inventory__location_image-view'),
    path('location_image/<int:pk>/delete',
         views.LocationImageDeleteView.as_view(),
         name='inventory__location_image-delete'),
    path('location/<int:location_pk>/images/upload',
         views.LocationImageUploadView.as_view(),
         name='inventory__location_image-upload'),

    path('location-note/<int:pk>', views.LocationNoteDetailView.as_view(),
         name='inventory__location_note-detail'),
    path('location-note/<int:location_pk>/create',
         views.LocationNoteCreateView.as_view(),
         name='inventory__location_note-create'),
    path('location-note/<int:pk>/update',
         views.LocationNoteUpdateView.as_view(),
         name='inventory__location_note-update'),
    path('location-note/<int:pk>/delete',
         views.LocationNoteDeleteView.as_view(),
         name='inventory__location_note-delete'),

    path('node_type/', views.NodeTypeListView.as_view(),
         name='inventory__node_type-list'),
    path('node_type/<int:pk>', views.NodeTypeDetailView.as_view(),
         name='inventory__node_type-detail'),
    path('node_type/create', views.NodeTypeCreateView.as_view(),
         name='inventory__node_type-create'),
    path('node_type/<int:pk>/update', views.NodeTypeUpdateView.as_view(),
         name='inventory__node_type-update'),
    path('node_type/<int:pk>/delete', views.NodeTypeDeleteView.as_view(),
         name='inventory__node_type-delete'),
    path('node_type/<int:pk>/role/create',
         views.RoleCreateView.as_view(initial_kwargs={'node_type': 'pk'}),
         name='inventory__node_type-role-create'),
    path('node_type/<int:pk>/node-port/create',
         views.NodePortCreateView.as_view(initial_kwargs={'node_type': 'pk'}),
         name='inventory__node_type-node_port-create'),
    path('node_type/<int:pk>/device/create',
         views.RoleCreateView.as_view(initial_kwargs={'node_type': 'pk'}),
         name='inventory__node_type-device-create'),

    path('node_type_image/<int:pk>', views.NodeTypeImageView.as_view(),
         name='inventory__node_type_image-view'),
    path('node_type_image/<int:pk>/delete',
         views.NodeTypeImageDeleteView.as_view(),
         name='inventory__node_type_image-delete'),
    path('node_type/<int:node_type_pk>/images/upload',
         views.NodeTypeImageUploadView.as_view(),
         name='inventory__node_type_image-upload'),

    path('role/', views.RoleListView.as_view(),
         name='inventory__role-list'),
    path('role/<int:pk>', views.RoleDetailView.as_view(),
         name='inventory__role-detail'),
    path('role/create', views.RoleCreateView.as_view(),
         name='inventory__role-create'),
    path('role/<int:pk>/update', views.RoleUpdateView.as_view(),
         name='inventory__role-update'),
    path('role/<int:pk>/delete', views.RoleDeleteView.as_view(),
         name='inventory__role-delete'),
    path('role/<int:pk>/device/create',
         views.DeviceCreateView.as_view(initial_kwargs={"role": "pk"}),
         name='inventory__role-device-create'),

    path('node_port_class/', views.NodePortClassListView.as_view(),
         name='inventory__node_port_class-list'),
    path('node_port_class/<int:pk>', views.NodePortClassDetailView.as_view(),
         name='inventory__node_port_class-detail'),
    path('node_port_class/create', views.NodePortClassCreateView.as_view(),
         name='inventory__node_port_class-create'),
    path('node_port_class/<int:pk>/update',
         views.NodePortClassUpdateView.as_view(),
         name='inventory__node_port_class-update'),
    path('node_port_class/<int:pk>/delete',
         views.NodePortClassDeleteView.as_view(),
         name='inventory__node_port_class-delete'),
    path('node_port_class/<int:pk>/node_port/create',
         views.NodePortCreateView.as_view(initial_kwargs={'port_class': 'pk'}),
         name='inventory__node_port_class-node_port-create'),

    path('node_port/', views.NodePortListView.as_view(),
         name='inventory__node_port-list'),
    path('node_port/<int:pk>', views.NodePortDetailView.as_view(),
         name='inventory__node_port-detail'),
    path('node_port/create', views.NodePortCreateView.as_view(),
         name='inventory__node_port-create'),
    path('node_port/<int:pk>/update', views.NodePortUpdateView.as_view(),
         name='inventory__node_port-update'),
    path('node_port/<int:pk>/delete', views.NodePortDeleteView.as_view(),
         name='inventory__node_port-delete'),

    path('device/', views.DeviceListView.as_view(),
         name='inventory__device-list'),
    path('device/<int:pk>', views.DeviceDetailView.as_view(),
         name='inventory__device-detail'),
    path('device/create', views.DeviceCreateView.as_view(),
         name='inventory__device-create'),
    path('device/<int:pk>/update', views.DeviceUpdateView.as_view(),
         name='inventory__device-update'),
    path('device/<int:pk>/delete', views.DeviceDeleteView.as_view(),
         name='inventory__device-delete'),
    path('device/<int:pk>/label.pdf', views.DeviceBarcodeView.as_view(),
         name='inventory__device-barcode'),
    path('device/<int:pk>/device_connection/scan',
         views.DeviceConnectionScannerView.as_view(
             initial_kwargs={'a_device': 'pk'}),
         name='inventory__device-device_connection-scan'),

    path('device_connection/scan',
         views.DeviceConnectionScannerView.as_view(),
         name='inventory__device_connection-scan'),
    path('device_connection/<int:pk>/delete',
         views.DeviceConnectionDeleteView.as_view(),
         name='inventory__device_connection-delete'),
    path('device_connection/', views.DeviceConnectionListView.as_view(),
         name='inventory__device_connection-list'),
    path('device_connection/<int:pk>',
         views.DeviceConnectionDetailView.as_view(),
         name='inventory__device_connection-detail'),
    path('device_connection/<int:pk>/update',
         views.DeviceConnectionUpdateView.as_view(),
         name='inventory__device_connection-update'),

    path('scan_barcode',
         TemplateView.as_view(template_name='inventory/scan.html'),
         name='inventory__scan_barcode'),
    path('scan_barcode_redirect/<str:encoded_barcode>',
         views.ScanDetailRedirectView.as_view(),
         name='inventory__scan_barcode_redirect'),
]

radio_inventory/inventory/models.py
from django.db import models
from django.urls import reverse_lazy
from django.contrib.auth.models import User

from reference_numbers.models import ReferenceNumber
from reference_numbers.mixins import ReferenceNumberMixin


# Create your models here.
class Location(ReferenceNumberMixin, models.Model):
    class Meta:
        ordering = ['description']

    reference_prefix = '1000'
    reference_number = models.OneToOneField(ReferenceNumber,
                                            on_delete=models.PROTECT)
    description = models.CharField(max_length=255)

    def get_absolute_url(self):
        return reverse_lazy('inventory__location-detail',
                            kwargs={'pk': self.pk})

    def __repr__(self):
        return (f"Location(description='{self.description}')")

    def __str__(self):
        return self.description

    def json(self):
        return {"pk": self.pk,
                "reference_number": self.reference_number_str(),
                "description": self.description,
               }

    def graphviz_dot(self):
        title = f"Location: {self.description}"
        node_names = []
        undirected_links = []
        directed_links = []

        for device in self.device_set.all():
            node_names.append((device.pk, device.node_type.short_name))

        # Implicit assumption device connections are within locations (not
        # between)
        connections = DeviceConnection.objects.filter(a_device__location=self)
        for device_connection in connections:
            a_connection_sink = \
                    device_connection.a_port.port_class.connection_sink
            b_connection_sink = \
                    device_connection.b_port.port_class.connection_sink

            if a_connection_sink == True and b_connection_sink == True:
                # TODO: Log this somewhere
                pass

            if ((not a_connection_sink and not b_connection_sink) or
                    (a_connection_sink and b_connection_sink)):
                undirected_links.append((device_connection.a_device.pk,
                                         device_connection.b_device.pk,
                                         device_connection.a_port.port_name,
                                         device_connection.b_port.port_name))

            if a_connection_sink and not b_connection_sink:
                directed_links.append((device_connection.b_device.pk,
                                       device_connection.a_device.pk,
                                       device_connection.b_port.port_name,
                                       device_connection.a_port.port_name))

            if b_connection_sink and not a_connection_sink:
                directed_links.append((device_connection.a_device.pk,
                                       device_connection.b_device.pk,
                                       device_connection.a_port.port_name,
                                       device_connection.b_port.port_name))


        graphviz_result = f"""
digraph {{
    nodesep=1.0;
    {'''
    '''.join([f'{node_name[0]} [ label="{node_name[1]}" ];'
                  for node_name in node_names])}

    subgraph undir {{
        edge [dir=none]
        {'''
        '''.join([f'{link[0]} -> {link[1]} '
                  f'[ taillabel="{link[2]}" headlabel="{link[3]}" '
                  'fontsize=8 color="blue" ]; '
                  for link in undirected_links])}
    }}

    subgraph dir {{
        {'''
        '''.join([f'{link[0]} -> {link[1]} '
                  f'[ taillabel="{link[2]}" headlabel="{link[3]}" '
                  'fontsize=8 color="blue" ]; '
                  for link in directed_links])}
    }}

    labelloc="t";
    label="{title}";
}}
        """

        return graphviz_result


class LocationImage(models.Model):
    location = models.ForeignKey(Location,
                                 on_delete=models.PROTECT)
    image = models.ImageField(width_field='width', height_field='height')
    width = models.PositiveIntegerField()
    height = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse_lazy('inventory__location_image-view',
                            kwargs={'pk': self.pk})


class LocationNote(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    note = models.TextField()
    creator = models.ForeignKey(User, on_delete=models.PROTECT)
    creation_time = models.DateTimeField(auto_now_add=True)
    last_modified_time = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return self.location.get_absolute_url()


class NodeType(models.Model):
    class Meta:
        ordering = ['type_name']

    type_name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=255, blank=True)

    def get_absolute_url(self):
        return reverse_lazy('inventory__node_type-detail',
                            kwargs={'pk': self.pk})

    def __repr__(self):
        return f"NodeType(type_name={self.type_name})"

    def __str__(self):
        return self.type_name

    def json(self):
        return {"pk": self.pk,
                "type_name": self.type_name
               }


class NodeTypeImage(models.Model):
    node_type = models.ForeignKey(NodeType,
                                  on_delete=models.PROTECT)
    image = models.ImageField(width_field='width', height_field='height')
    width = models.PositiveIntegerField()
    height = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse_lazy('inventory__node_type_image-view',
                            kwargs={'pk': self.pk})


class Role(models.Model):
    class Meta:
        ordering = ['description']

    description = models.CharField(max_length=255)
    # node_type is an indication to the list when assigning a Device's role
    # and is also used to validate the role that was set. Doesn't really need
    # to be exposed to the user as it's not useful after validation.
    node_type = models.ForeignKey(NodeType, on_delete=models.PROTECT)

    def get_absolute_url(self):
        return reverse_lazy('inventory__role-detail',
                            kwargs={'pk': self.pk})

    def __repr__(self):
        return (f"Role(description={self.description}, "
                f"node_type={self.node_type})")

    def __str__(self):
        return self.description

    def json(self):
        return {"pk": self.pk,
                "description": self.description
               }


class NodePortClass(models.Model):
    class Meta:
        ordering = ['class_name']

    class_name = models.CharField(max_length=255)
    compatible_opposite_ports = models.ManyToManyField("NodePortClass",
                                                       symmetrical=True,
                                                       blank=True)
    # If this is a "connection_sink" then connection with a non-sink will form
    # an arrow to this node. Two connection_sink's should not connect to each
    # other. Two connection_sink == false classes connected to each other
    # implies an undirected link.
    # TODO: Some sort of checking on save compatible_opposite_ports to check
    # not being marked compatible with connection_sink == True on both ends.
    connection_sink = models.BooleanField()

    def get_absolute_url(self):
        return reverse_lazy('inventory__node_port_class-detail',
                            kwargs={'pk': self.pk})

    def __repr__(self):
        return f"NodePortClass(class_name={self.class_name})"

    def __str__(self):
        return self.class_name

    def json(self):
        return {"pk": self.pk,
                "class_name": self.class_name,
                "compatible_opposite_ports":
                    [{"pk": other.pk,
                      "class_name": other.class_name,
                     } for other in self.compatible_opposite_ports_set.all()],
               }


class NodePort(models.Model):
    class Meta:
        ordering = ['node_type', 'port_class', 'port_name']

    node_type = models.ForeignKey(NodeType,
                                  on_delete=models.PROTECT)
    port_name = models.CharField(max_length=255)
    port_class = models.ForeignKey(NodePortClass,
                                   on_delete=models.PROTECT)

    def get_absolute_url(self):
        return reverse_lazy('inventory__node_port-detail',
                            kwargs={'pk': self.pk})

    def __repr__(self):
        return (f"NodePort(node_type={self.node_type!r}, "
                f"port_name={self.port_name}, "
                f"port_class={self.port_class!r})")

    def __str__(self):
        return (f"{self.port_name} of {self.node_type}" +
                ("" if self.port_class is None else
                 f" of type {self.port_class}"))

    def json(self):
        return {"pk": self.pk,
                "node_type": self.node_type.json(),
                "port_name": self.port_name,
                "port_class": self.port_class.json(),
               }


# TODO: Check device and any connected devices are in the same location on
# save
# TODO: Changing node_type requires breaking all links (ports need to change)
class Device(ReferenceNumberMixin, models.Model):
    class Meta:
        ordering = ['location', 'node_type', 'emulab_node_name',
                    'serial_number', 'reference_number']
    reference_prefix = '2000'
    reference_number = models.OneToOneField(ReferenceNumber,
                                            on_delete=models.PROTECT)

    emulab_node_name = models.CharField(max_length=255, unique=True, null=True,
                                        blank=True)
    node_type = models.ForeignKey(NodeType,
                                  on_delete=models.PROTECT)
    serial_number = models.CharField(max_length=255, blank=True)

    location = models.ForeignKey(Location,

radio_inventory/inventory/templates/inventory/location_confirm_delete.html
{% extends "delete.html" %}

radio_inventory/inventory/templates/inventory/location_detail.html
{% extends "base.html" %}

{% block title %}Inventory Location Details{% endblock %}

{% block body %}
<div>
    {{ object.description }}
    <a href="{% url 'inventory__location-update' pk=object.pk %}">edit</a>
</div>
<div>
    <a href="{% url 'inventory__location-barcode' pk=object.pk %}"
        target="_blank">barcode</a>
</div>
<div>
    <a href="{% url 'inventory__location-connections' pk=object.pk %}"
        target="_blank">connections</a>
</div>

<h3>Notes</h3>
<table>
    <tr>
        <th>Creator</th>
        <th>Creation Time</th>
        <th>Last Updated</th>
        <th>Note</th>
        {% if perms.inventory.add_locationnote or perms.inventory.change_locationnote or perms.inventory.delete_locationnote %}
        <th class="edit_delete_column">
            {% if perms.inventory.add_locationnote %}
            <a href="{% url 'inventory__location_note-create' location_pk=object.pk %}">+</a>
            {% endif %}
        </th>
        {% endif %}
    </tr>
    {% for location_note in object.locationnote_set.all %}
    <tr>
        <td>
            {{ location_note.creator }}
        </td>
        <td>
            {{ location_note.creation_time }}
        </td>
        <td>
            {{ location_note.last_modified_time }}
        </td>
        <td>
            {{ location_note.note|linebreaksbr }}
        </td>
        {% if perms.inventory.add_locationnote or perms.inventory.change_locationnote or perms.inventory.delete_locationnote %}
        <td>
            {% if perms.inventory.change_locationnote %}
            <a href="{% url 'inventory__location_note-update' pk=location_note.pk %}">edit</a>
            {% endif %}
            {% if perms.inventory.delete_locationnote %}
            <a href="{% url 'inventory__location_note-delete' pk=location_note.pk %}">x</a>
            {% endif %}
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>

<h3>Devices</h3>

<table>
    <tr>
        <th>Reference Number</th>
        <th>Emulab Node Name</th>
        <th>Node Type</th>
        <th>Serial Number</th>
        <th>Location</th>
        <th>Role</th>
        <th>Barcode</th>
        {% if perms.inventory.add_device or perms.inventory.change_device or perms.inventory.delete_device %}
        <th class="edit_delete_column">
            {% if perms.inventory.add_device %}
            <a href="{% url 'inventory__location-device-create' pk=object.pk %}">+</a>
            {% endif %}
        </th>
        {% endif %}
    </tr>
    {% for device in object.device_set.all %}
    <tr>
        <td>
            <a href="{% url 'inventory__device-detail' pk=device.pk %}">
                {{ device.reference_number_str }}
            </a>
        </td>
        <td>{{ device.emulab_node_name }}</td>
        <td>
            <a href="{{ device.get_absolute_url }}">
                {{ device.node_type }}
            </a>
        </td>
        <td>{{ device.serial_number }}</td>
        <td>
            <a href="{{ device.location.get_absolute_url }}">
                {{ device.location }}
            </a>
        </td>
        <td>
            {% if device.role is not None %}
            <a href="{{ device.role.get_absolute_url }}">
            {% endif %}
                {{ device.role }}
            {% if device.role is not None %}
            </a>
            {% endif %}
        </td>
        <td>
            <a href="{% url 'inventory__device-barcode' pk=device.pk %}"
                target="_blank">barcode</a>
        </td>
        {% if perms.inventory.add_device or perms.inventory.change_device or perms.inventory.delete_device %}
        <td>
            {% if perms.inventory.change_device %}
            <a href="{% url 'inventory__device-update' pk=device.pk %}">edit</a>
            {% endif %}
            {% if perms.inventory.delete_device %}
            <a href="{% url 'inventory__device-delete' pk=device.pk %}">x</a>
            {% endif %}
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>


<h3>Images</h3>

<table>
    <tr>
        <th>
            Image
        </th>
        {% if perms.inventory.add_locationimage or perms.inventory.delete_locationimage %}
        <th>
            {% if perms.inventory.add_locationimage %}
            <a href="{% url 'inventory__location_image-upload' location_pk=object.pk %}">
                +
            </a>
            {% endif %}
        </th>
        {% endif %}
    </tr>
    {% for image in object.locationimage_set.all %}
    <tr>
        <td>
            <img src="{{ image.get_absolute_url }}"
                 width="{{ image.width }}"
                 height="{{ image.height }}"></img>
        </td>
        {% if perms.inventory.add_locationimage or perms.inventory.delete_locationimage %}
        <td>
            {% if perms.inventory.delete_locationimage %}
            <a href="{% url 'inventory__location_image-delete' pk=image.pk %}">x</a>
            {% endif %}
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>


{% endblock %}

radio_inventory/inventory/templates/inventory/location_form.html
{% extends "form.html" %}

radio_inventory/inventory/templates/inventory/location_option_widget.html
<option value="{{ widget.value|stringformat:'s' }}"{% include "django/forms/widgets/attrs.html" %}
 data-reference-number="{{ widget.value.instance.reference_number_str }}"
 >{{ widget.label }}</option>

radio_inventory/inventory/templates/inventory/locationnote_form.html
{% extends "form.html" %}

radio_inventory/inventory/templates/inventory/nodeport_confirm_delete.html
{% extends "delete.html" %}

radio_inventory/inventory/templates/inventory/nodeport_detail.html
{% extends "base.html" %}

{% block title %}Node Port Details{% endblock %}

{% block body %}
<div>
    <a href="{% url 'inventory__node_port-update' pk=object.pk %}">edit</a>
</div>
<table>
    <tr>
        <th>Node Type</th>
        <td>
            <a href="{{ object.node_type.get_absolute_url }}">
                {{ object.node_type }}
            </a>
        </td>
    </tr>
    <tr>
        <th>Port Name</th>
        <td>{{ object.port_name }}</td>
    </tr>
    <tr>
        <th>Port Class</th>
        <td>
            <a href="{{ object.port_class.get_absolute_url }}">
                {{ object.port_class }}
            </a>
        </td>
    </tr>
</table>

{% endblock %}

radio_inventory/inventory/templates/inventory/nodetype_detail.html
{% extends "base.html" %}

{% block title %}Node Type Details{% endblock %}

{% block body %}
<div>
    <a href="{% url 'inventory__node_type-update' pk=object.pk %}">edit</a>
</div>

<h3>Details</h3>

<table>
    <tr>
        <th>Node Type</th>
        <td>{{ object.type_name }}</td>
    </tr>
    <tr>
        <th>Short Name</th>
        <td>{{ object.short_name }}</td>
    </tr>
</table>


<h3>Roles</h3>

<table>
    <tr>
        <th>Role</th>
        <th>Node Type</th>
        {% if perms.inventory.add_role or perms.inventory.change_role or perms.inventory.delete_role %}
        <th class="edit_delete_column">
            {% if perms.inventory.add_role %}
            <a href="{% url 'inventory__node_type-role-create' pk=object.pk %}">+</a>
            {% endif %}
        </th>
        {% endif %}
    </tr>
    {% for role in object.role_set.all %}
    <tr>
        <td>
            <a href="{{ role.get_absolute_url }}">
                {{ role.description }}
            </a>
        </td>
        <td>
            <a href="{{ role.node_type.get_absolute_url }}">
                {{ role.node_type }}
            </a>
        </td>
        {% if perms.inventory.add_role or perms.inventory.change_role or perms.inventory.delete_role %}
        <td>
            {% if perms.inventory.change_role %}
            <a href="{% url 'inventory__role-update' pk=role.pk %}">edit</a>
            {% endif %}
            {% if perms.inventory.delete_role %}
            <a href="{% url 'inventory__role-delete' pk=role.pk %}">x</a>
            {% endif %}
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>

<h3>Ports</h3>

<table>
    <tr>
        <th>Port Name</th>
        <th>Node Type</th>
        <th>Port Class</th>
        {% if perms.inventory.add_nodeport or perms.inventory.change_nodeport or perms.inventory.delete_nodeport %}
        <th class="edit_delete_column">
            {% if perms.inventory.add_nodeport %}
            <a href="{% url 'inventory__node_type-node_port-create' pk=object.pk %}">+</a>
            {% endif %}
        </th>
        {% endif %}
    </tr>
    {% for node_port in object.nodeport_set.all %}
    <tr>
        <td>
            <a href="{{ node_port.get_absolute_url }}">
                {{ node_port.port_name }}
            </a>
        </td>
        <td>
            <a href="{{ node_port.node_type.get_absolute_url }}">
                {{ node_port.node_type }}
            </a>
        </td>
        <td>
            <a href="{{ node_port.port_class.get_absolute_url }}">
                {{ node_port.port_class }}
            </a>
        </td>
        {% if perms.inventory.add_nodeport or perms.inventory.change_nodeport or perms.inventory.delete_nodeport %}
        <td>
            {% if perms.inventory.change_nodeport %}
            <a href="{% url 'inventory__node_port-update' pk=node_port.pk %}">edit</a>
            {% endif %}
            {% if perms.inventory.delete_nodeport %}
            <a href="{% url 'inventory__node_port-delete' pk=node_port.pk %}">x</a>
            {% endif %}
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>

<h3>Devices</h3>

<table>
    <tr>
        <th>Reference Number</th>
        <th>Emulab Node Name</th>
        <th>Node Type</th>
        <th>Serial Number</th>
        <th>Location</th>
        <th>Role</th>
        <th>Barcode</th>
        {% if perms.inventory.add_device or perms.inventory.change_device or perms.inventory.delete_device %}
        <th class="edit_delete_column">
            {% if perms.inventory.add_device %}
            <a href="{% url 'inventory__node_type-device-create' pk=object.pk %}">+</a>
            {% endif %}
        </th>
        {% endif %}
    </tr>
    {% for device in object.device_set.all %}
    <tr>
        <td>
            <a href="{% url 'inventory__device-detail' pk=device.pk %}">
                {{ device.reference_number_str }}
            </a>
        </td>
        <td>{{ device.emulab_node_name }}</td>
        <td>
            <a href="{{ device.get_absolute_url }}">
                {{ device.node_type }}
            </a>
        </td>
        <td>{{ device.serial_number }}</td>
        <td>
            <a href="{{ device.location.get_absolute_url }}">
                {{ device.location }}
            </a>
        </td>
        <td>
            <a href="{{ device.role.get_absolute_url }}">
                {{ device.role }}
            </a>
        </td>
        <td>
            <a href="{% url 'inventory__device-barcode' pk=device.pk %}"
                target="_blank">barcode</a>
        </td>
        {% if perms.inventory.add_device or perms.inventory.change_device or perms.inventory.delete_device %}
        <td>
            {% if perms.inventory.change_device %}
            <a href="{% url 'inventory__device-update' pk=device.pk %}">edit</a>
            {% endif %}
            {% if perms.inventory.delete_device %}
            <a href="{% url 'inventory__device-delete' pk=device.pk %}">x</a>
            {% endif %}
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>


<h3>Images</h3>

<table>
    <tr>
        <th>
            Image
        </th>
        {% if perms.inventory.add_nodetypeimage or perms.inventory.delete_nodetypeimage %}
        <th>
            {% if perms.inventory.add_nodetypeimage %}
            <a href="{% url 'inventory__node_type_image-upload' node_type_pk=object.pk %}">
                +
            </a>
            {% endif %}
        </th>
        {% endif %}
    </tr>
    {% for image in object.nodetypeimage_set.all %}
    <tr>
        <td>
            <img src="{{ image.get_absolute_url }}"
                 width="{{ image.width }}"
                 height="{{ image.height }}"></img>
        </td>
        {% if perms.inventory.add_nodetypeimage or perms.inventory.delete_nodetypeimage %}
        <td>
            {% if perms.inventory.delete_nodetypeimage %}
            <a href="{% url 'inventory__node_type_image-delete' pk=image.pk %}">x</a>
            {% endif %}
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>


{% endblock %}